language: python
python:
  - "2.7"
  - "3.4"

install:
  - "pip install nose-cov"
  - "pip install python-coveralls"
  - "pip install ."

# Run test
script:
  - nosetests --with-cov --cov=dispatch --cov-config=.coveragerc --logging-level=DEBUG

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
